FROM node:20
WORKDIR /app
COPY etl etl
COPY api/prisma api/prisma
RUN cd etl \
  && npm install \
  && npm install prisma@5.8.0 @prisma/client@5.8.0 \
  && npx prisma@5.8.0 generate --schema=../api/prisma/schema.prisma
CMD ["node","etl/worker.js"]
